SET TALK OFF
DO WHILE.T.
CLEAR
TEXT
FUNCTII OFERITE
1.ADAUGARE
2.LISTARE
3.LISTARE PRIMELE X INREGISTRARI
4.STERGERE DUPA NUME
5.MARCARE PENTRU STERGERE DUPA NUME
6.CONFIRMA STERGEREA
7.ACORDARE BURSA STUDENTI CU MEDIA PESTE 9
8.MARIRE BURSA PT STUDENTI CARE AU MEDIA 10 CU X%
0.INCHIDERE
ENDTEXT
WAIT TO R
IF.NOT. R $ '123456780t'
? 'FUNCTIA' + R + ' INEXISTENTA'
WAIT
LOOP
ENDIF
DO CASE
CASE R='1'
USE Studenti
APPEND
CASE R='2'
USE Studenti.dbf
LIST
CASE R='3'
USE Studenti.dbf
X=VAL(accept('X'))
DISP FOR RECNO()<X
CASE R='0'
USE
RETURN
ENDCASE
ENDDO

